<a href="https://colab.research.google.com/github/yoshinaga2904/Bootcamp-Alura/blob/main/Projeto_final_bootcamp_Alura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#COVID-19 - Dados clínicos para avaliar o diagnóstico
Dados do Sírio-Libanês para IA e Analytics pela equipe de Data Intelligence

##Contexto
A pandemia de COVID-19 atingiu o mundo inteiro, sobrecarregando os sistemas de saúde - despreparados para uma solicitação tão intensa e demorada de leitos de UTI, profissionais, equipamentos de proteção individual e recursos de saúde.
O Brasil registrou o primeiro caso COVID-19 em 26 de fevereiro e atingiu a transmissão na comunidade em 20 de março.

Há urgência na obtenção de dados precisos para melhor prever e preparar os sistemas de saúde e evitar colapsos, definido pela necessidade de leitos de UTI acima da capacidade (assumindo que recursos humanos, EPIs e profissionais estejam disponíveis), usando dados clínicos individuais - em vez de dados epidemiológicos e populacionais .

Prever a admissão na UTI de casos confirmados de COVID-19.
Com base nos dados disponíveis, é viável prever quais pacientes precisarão de suporte em unidade de terapia intensiva?
O objetivo é fornecer aos hospitais terciários e trimestrais a resposta mais precisa, para que os recursos da UTI possam ser arranjados ou a transferência do paciente possa ser agendada.

Preveja NÃO admissão à UTI de casos COVID-19 confirmados.
Com base na subamostra de dados amplamente disponíveis, é viável prever quais pacientes precisarão de suporte de unidade de terapia intensiva?
O objetivo é fornecer aos hospitais locais e temporários uma resposta boa o suficiente, para que os médicos de linha de frente possam dar alta com segurança e acompanhar remotamente esses pacientes.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
dados = pd.read_excel("https://github.com/yoshinaga2904/Bootcamp-Alura/raw/main/Kaggle_Sirio_Libanes_ICU_Prediction.xlsx")

dados.head()

   PATIENT_VISIT_IDENTIFIER  AGE_ABOVE65  ...    WINDOW  ICU
0                         0            1  ...       0-2    0
1                         0            1  ...       2-4    0
2                         0            1  ...       4-6    0
3                         0            1  ...      6-12    0
4                         0            1  ...  ABOVE_12    1

[5 rows x 231 columns]

In [47]:
def analise_dados(dado: pd.DataFrame):
  linhas = dado.shape[0]
  colunas = dado.shape[1]
  
  valor_nan = dado.isnull().any().any()
  if valor_nan:
    qtde_nan = dado.isnull().sum().values.sum()

  tipos = list(set(dado.dtypes.values))

  print(f"Número de linhas = {linhas}\nNúmero de colunas = {colunas}")
  print(f"Há valores vazios? {valor_nan}\nQuantdade de valores vazios no dataset = {qtde_nan}")
  print(f"Tipo dos dados no DataFrame = {tipos}")

In [48]:
analise_dados(dados)

Número de linhas = 1925
Número de colunas = 231
Há valores vazios? True
Quantdade de valores vazios no dataset = 223863
Tipo dos dados no DataFrame = [dtype('int64'), dtype('float64'), dtype('O')]